image: Visual Studio 2017

platform: Any CPU
configuration: Release

shallow_clone: true
skip_tags: true

environment:
  GITHUB_AUTH_TOKEN:
    secure: e24gj/T2VZ5R4XwbNUwj+eu4FbHEqWKUhuvNKXcp4dRPxj8lgW3AbWgSitK5kzek

init:
  - ps: |
      If (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
        $env:IS_NOT_PR = "true"
      }

before_build:
  - nuget restore src\PocketGaugerPlugin.sln

build:
  project: src\PocketGaugerPlugin.sln

artifacts:
  - path: src\PocketGauger\deploy\Release\PocketGauger.plugin
    name: ThePlugin
    type: file

deploy:
  - provider: GitHub
    tag: v$(APPVEYOR_BUILD_VERSION)
    release: PocketGauger plugin $(APPVEYOR_BUILD_VERSION)
    description: ''
    artifact: ThePlugin
    auth_token: $(GITHUB_AUTH_TOKEN)
    on:
      is_not_pr: true
